class StickerIds:
    hello =  'CAACAgIAAxkBAAEBIctfJa58obHD4CJEHblbxGfJUiHj3QACXgADpDaFD6q-yyNYCWedGgQ'
    loh = 'CAACAgIAAxkBAAEBIkRfJmExF0sda5m_M_TLFwYqJIQBSwACNQADpDaFD37hzVCG6X4fGgQ'
    no_mood = 'CAACAgIAAxkBAAEBIklfJm6BEPp8Cyj3MUwPIJKzI16eGgACOAADpDaFDzCOfRRixp7sGgQ'
    done = 'CAACAgIAAxkBAAEBIyRfJwirCcxgttNh_p4hrtJ9I_RxpQACSwADpDaFD1s78iMvZpn0GgQ'
    years_25 = 'CAACAgIAAxkBAAEBI-ZfJ9iH1beVbF4NtB-AmzYDuH_kOQACQAADpDaFD8wX34DNTnlEGgQ'
    rachal = 'CAACAgIAAxkBAAEBJBNfKFVe3u0E6SliArsaYcx-i1IosAACdQADpDaFD9g_eFds2X1rGgQ'
    zakruzhilas = 'CAACAgIAAxkBAAEBJ1RfKvOogS9hA_vEZDoRZDsL0VJ3GgACWAADpDaFD1OQHIIPP0eCGgQ'
